version: '3.8'
services:
  app:
    image: your-dockerhub-username/stock-price-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
