version: '3.8'

services:
  app:
    image: stock-price-app
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py 

GitHub CLI api # https://cli.github.com/manual/gh_api gh api \ -H "Accept: application/vnd.github+json" \ -H "X-GitHub-Api-Version: 2022-11-28" \ /orgs/ORG/docker/conflicts