# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  say-hello:
    # Specify the execution environment.
    docker:
      - image: cimg/base:stable

    # Add steps to the job
    steps:
      - checkout
      - run:
          name: "Print a friendly greeting"
          command: "echo Hello, friendly user!"

# Orchestrate jobs using workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello

